version: '3'

services:
  source_db:
    image: postgres:latest
    container_name: source_db
    restart: always
    environment:
      - POSTGRES_DB=${SRC_POSTGRES_DB}
      - POSTGRES_USER=${SRC_POSTGRES_USER}
      - POSTGRES_PASSWORD=${SRC_POSTGRES_PASSWORD}
    ports:
      - ${SRC_POSTGRES_PORT}:5432
    volumes:
      - ./source_data:/docker-entrypoint-initdb.d
      - source-vol:/var/lib/postgresql/data

volumes:
  source-vol:
